### ISSUE TITLE
Any way to pass a pem key to connect on Amazon EC2?

### ISSUE THREAD

**Issue by tbergeron** [fadion/Maneuver#10]
Hi,

I'd like to know if there's any way to pass a pem key to connect on Amazon EC2?

Suggestions are welcome.

Thanks and keep up the good work :+1:

**Comment by tbergeron** [comment]
Another quick question: any way of running tasks after a deploy? composer update for example?

**Comment by fadion** [comment]
I believe adding an identity file is doable. Give me a couple of days to check it out.

As for tasks, currently it's not possible.

**Comment by fadion** [comment]
Added the ability to pass options to Bridge, the library Maneuver uses for ssh/ftp transfers. You just define options like below:

```
'development' => [
  'scheme' => 'ftp',
  'host' => 'someserver',
  /* ... */
  'options' => [
    'pubkey' => 'pubkey_file'
  ]
]
```

The `pubkey` option expects a file location and you'll have to experiment with that. I haven't actually tried it with a real-world scenario. Hope it does the job for you.

**Comment by tbergeron** [comment]
Great! Thanks for the quick response, I'll go try it now :D
