### ISSUE TITLE
Disable check .gitignore for ignore files

### ISSUE THREAD

**Issue by orloffv** [fadion/Maneuver#12]
How to disable check .gitignore OR allowed(wild card) some directory?
Case: 
i use bower for js dependencies, on my server not installed nodejs.
In .gitignore - ignored /js_assets/
But i want sync /js_assets/ to my production server
L5

**Comment by fadion** [comment]
I've been thinking to add a config option to force upload ignored files, as this feature has been requested by a few people. It's in the waiting list and I'll add it as soon as I can.

For now, you'll have to either remove those directories from .gitignore or upload them manually. I'm closing the issue.
