### ISSUE TITLE
Deploy issue when app is not in the root git repository

### ISSUE THREAD

**Issue by sarbull** [fadion/Maneuver#13]
Deploy is not working when the app is not in the root git repository.
Right now i have my app in
```bash
git-repo/
git-repo/application
git-repo/application/app
git-repo/application/public
...
```
And when i run
```bash
php artisan deploy
'/git-repo/application' is not a Git repository.
```
I get this ^

Also i think laravel needs the vendor files in order to make the app work, so i think that this deploy system needs some sort of
```php
return [
   'ignored' => [],
   'force' => [
      'vendor' // in order to force deploy the ignored files from git.
   ]
];
```

Thanks!

**Comment by sarbull** [comment]
Big :+1: for this ftp deploy system, specially on laravel apps with shared hosting!

**Comment by fadion** [comment]
Thanks for the kind words.

Maneuver reads the `.git` directory to check if it's a git repo, so yes, it won't work outside of the root. It's supposed to work that way and I don't believe it's much of a problem.

As for the `vendor` directory, I plan to add a force option and hopefully I can look into it asap. For now, your only option is to remove the `vendor` from `.gitignore`.

**Comment by sarbull** [comment]
@fadion yes, but i have to create a new commit and then re add the folder into the gitignore file.. it's kinda weird.

I think that 'force' thing could solve everything.. If there is anything i can help you with this, i'd be glad.

**Comment by sarbull** [comment]
The #13 Issue. Haha!

**Comment by sarbull** [comment]
```
 It's supposed to work that way and I don't believe it's much of a problem.
```

Yes but, for example i like to keep in my git repo structured like this:
```
/application
/design
README.md
```

What could be the best solution for this?

**Comment by fadion** [comment]
`/application` and `/design` are the same repo and you want just the `application/` folder pushed to the server?

**Comment by sarbull** [comment]
@fadion yes

**Comment by fadion** [comment]
Git doesn't work that way. Maneuver just reads the diff and gets what files have changed for the whole git repo, not parts of it. You'll have to organize the application and design in different repos for Maneuver to work as you expect.

**Comment by sarbull** [comment]
I see. Ok, looking forward on that force feature. Also check #14. Thanks!
