### ISSUE TITLE
Deploying branches

### ISSUE THREAD

**Issue by sarbull** [fadion/Maneuver#14]
Is there a command for deploying a certain branch? Such as
```bash
php artisan deploy --branch=feature-1
```

**Comment by fadion** [comment]
No branch option, but you can easily do it as:

```bash
git checkout feature-1
php artisan deploy
```

**Comment by bee-interactive** [comment]
Hi!

I'm stucked.. Every time I want to deploy, it starts from scratch.. I checked my .revision file and my last commit, the match. My files are correctly uploaded to the right server, but it uploads all the files every time.. Any idea why is that?

Thanks!
