### ISSUE TITLE
cURL backend error on l5 branch

### ISSUE THREAD

**Issue by rigelk** [fadion/Maneuver#15]
Hello,

Not sure if I’m doing it wrong, but following the readme lead me to having the following error on `php artisan deploy`

```
+ --------------- § --------------- +
» Server: developmentUnable to check if file/folder exists using cURL backend. This functionality has not yet been implemented.
```

Is it due to a missing dep ? A misconfiguration ? Or is it simply that my site is unreachable ?

**Comment by fadion** [comment]
I'm using [Bridge](https://github.com/banago/Bridge) for the backends and it hasn't implemented cURL fully yet. Actually Maneuver it's supposed to be used with FTP or SFTP. Anyway, if you want, you can open an issue at Bridge requesting to fully implement cURL.

**Comment by banago** [comment]
@rigelk you need to install `php_ssh2` extension and everything will work fine. cURL is meant to be a fallback when `php_ssh2` is missing.

**Comment by rigelk** [comment]
@fadion do you mean Maneuver actually doesn’t support FTP and sFTP as advertised ?
@banago i installed `php_ssh2` yet still have the same error. `php -m | grep ssh2` shows ssh2 activated and so does the phpinfo().

**Comment by fadion** [comment]
I meant just the opposite, that it supports FTP and sFTP. @banago is the creator of Bridge and will provide better help than me.

**Comment by banago** [comment]
@rigelk seems something is wrong on your system. FTP does not fall back to cURL as far as I can remember, only SFTP and SSH do. What system are you on?

**Comment by rigelk** [comment]
@banago i’m running on archlinux. I installed php-ssh2 through AUR via the [php-ssh-git](https://aur.archlinux.org/packages/php-ssh-git/) package. I then activated `extension=ssh2.so` and did a `systemctl restart httpd` to restart the php dæmon.

**Comment by banago** [comment]
@rigelk seems you are set. However, my last guess now would be you check `extension=ssh2.so` is set for both `php.ini`, webserver and CLI. At least in Ubuntu I had to update both of them. To test you really have `php_ssh2` installed, please run this in a little file and see what you get:

		if(!function_exists('ssh2_connect')) {
			return false;
		}
If you get false, you are not done with configuration yet.

**Comment by rigelk** [comment]
@banago i did a `php -r 'echo function_exists("ssh2_connect") ? "ssh2 supported\n" : "ssh2 unsupported\n";'`. Seems like the function exists.

**Comment by banago** [comment]
I don't have any clues. This is not an expected behavior if php_ssh2 is active and works well. Sorry I cannot help further.

**Comment by rigelk** [comment]
Thanks anyway ! I will try investigating further on the php_ssh2 side

**Comment by fadion** [comment]
@rigelk any update on this issue?
