### ISSUE TITLE
[l5 branch] requirements in composer.json are too strict to work with L5.1

### ISSUE THREAD

**Issue by ndrskln** [fadion/Maneuver#17]
To enable users to work with more recent versions of Laravel 5 it seems reasonable to me to require only `5.*` instead of `5.0.*` since Laravel 5.0 is already almost outdated again.

This should be working anyway, it should lower your maintenance effort and it should make the amazing Maneuver package available to more developers (for the next years)!
```
        "illuminate/support": "5.*",
        "illuminate/console": "5.*",
        "illuminate/config": "5.*",
```

**Comment by fadion** [comment]
You are right. The composer file was actually updated by a PR and didn't really think about it. Thanks for the kinds words too :)
