### ISSUE TITLE
ignored path not honoured

### ISSUE THREAD

**Issue by ockam** [fadion/Maneuver#18]
Using the dev-l5 branch on a Laravel 5.1 project, my config contains the following ignored paths:

```
    'ignored' => [
        'laravel/resources/assets/*',
    ]
```
But the assets folders gets created anyway.

Am I doing it wrong or this is a bug?

**Comment by fadion** [comment]
Sorry for the late reply. I've missed this issue.

The `ignored` array expects a list of files, not folders. It was thought as a simple way to add a few files from being deployed. You can either add `assets` to .gitignore or add the full list of files in the `ignored` config option, which could be bothersome.

You can also check that the [implementation is a simple array_diff()](https://github.com/fadion/Maneuver/blob/master/src/Fadion/Maneuver/Deploy.php#L125) to remove the ignored list from the currently built files list.
