### ISSUE TITLE
php requirement in composer.json became too strict to work with L5.0 on deb7 with php5.4

### ISSUE THREAD

**Issue by justxx** [fadion/Maneuver#19]
Hi Fadion,
First of all big thank you for this awesome package. Really helpful at third party servers.
This last "compatibility for future" update after the "PR" update brings some new incompatibility, because php requirement was changed from 5.4 to 5.5 and in the case where you want to install Laravel 5.0 on a Debian 7 (where the default php is 5.4 actually and enough for L5.0) the composer update will fail.
Php requirement for Laravel 5.0 is >=5.4 for Laravel 5.1 is >=5.5.9
Troubleshoot so far::
I could update php of course, but I have no access on the production server to do that.
I tried to put the previous "PR" commit to the composer json like this:
,"fadion/maneuver": "dev-l5#903ed57de6b7020038ae6a2a7669317a3a2e2766"
but it fails in the same way by unknown reason and these commits are not versioned unfortunately :(
Any solution welcome

**Comment by fadion** [comment]
Just pushed a dedicated branch for you to try, with requirements for Laravel 5.0 and PHP 5.4. Use `dev-l5php54` in your composer file. If it doesn't work, I'm actually out of ideas.

**Comment by justxx** [comment]
Works like charm!
You made my day, million thanks.

**Comment by fadion** [comment]
Glad it worked.
