### ISSUE TITLE
in laravel fresh installation once you install it stops working php artisan

### ISSUE THREAD

**Issue by hardikdangar** [fadion/Maneuver#20]
After instllation,

i try to copy config files via,
php artisan vendor:publish

but it stops at following error, possibly issue with config file?

PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php:1341
Stack trace:
#0 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1341): ReflectionClass->__construct('log')
#1 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1295): Illuminate\Container\Container->build('log', Array)
#2 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1857): Illuminate\Container\Container->make('log', Array)
#3 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1396): Illuminate\Foundation\Application->make('log')
#4 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1373): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1359): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php(1295): Illu in /home/deploy/deploy/code/project/code/bootstrap/cache/compiled.php on line 1341

**Comment by fadion** [comment]
The error isn't saying anything specific to Maneuver. It just can't find a `log` class, which Maneuver isn't using anywhere. Normally you should get the same message with any artisan command, not just `vendor:publish`.

Take a look at [this discussion](https://laracasts.com/discuss/channels/general-discussion/reflectionexception-class-log-does-not-exist-in-homevagrantcode). Some people have had the same issue with Laravel.

**Comment by hardikdangar** [comment]
I believe its related to many be some dependencies in Maneuver because if i git checkout composer.json and do fresh composer install then my laravel setup works fine but as soon as i try to install maneuver it doesn't work. I am using laravel 5.2.7 ( ubuntu 14.04 ) if you want to test.

**Comment by fadion** [comment]
Just tried it out with a fresh installation of Laravel 5.2.28 on OSX and it installed and deployed correctly. Not sure what's happening on your side.
