### ISSUE TITLE
SSH2 Pecl extension not installed error

### ISSUE THREAD

**Issue by azamatsulaiman** [fadion/Maneuver#21]
I get

> Oh snap: ssh2 PECL extension is not installed. Please install it to use ssh.

after php artisan deploy command on L5

**Comment by fadion** [comment]
This was discussed on #5. Basically, you'll need to have the [ssh2](http://php.net/book.ssh2) PECL extension installed.

**Comment by alexhoma** [comment]
But where do you need to install this? I'm running my Laravel on local server. The one that comes with laravel -->` php artisan serve` command
Or do I need to install it on my production server?

Thanks @fadion :)

**Comment by fadion** [comment]
I don't believe you can install extensions for the built-in PHP server. I'd highly recommend setting up vagrant with homestead, an operations that won't take more than 5 minutes. Then you can easily install ssh2 in the vagrant box.

**Comment by alexhoma** [comment]
Thank you @fadion, it worked as expected with vagrant and homestead.

**Comment by fadion** [comment]
@alexhoma Glad I was of help.
