### ISSUE TITLE
[Question] Any reason why this hasn't been tagged for Laravel 5?

### ISSUE THREAD

**Issue by kaidesu** [fadion/Maneuver#24]
Just curious if theres anything that's holding it back that you could use some help on!

**Comment by fadion** [comment]
I haven't tested it on anything higher than the initial Laravel 5.0. If you want to help by trying it out and testing in Laravel 5.1+, that'd be great.

**Comment by vsimic80** [comment]
Just tried this using Laravel 5.5.3 - after running 'composer update' here is output:

$ composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fadion/maneuver 1.0 requires banago/bridge dev-master -> satisfiable by banago/bridge[dev-master] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - fadion/maneuver 1.0.1 requires illuminate/config 4.2.* -> satisfiable by illuminate/config[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - fadion/maneuver 1.0.2 requires illuminate/config 4.2.* -> satisfiable by illuminate/config[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/config v4.2.1|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.12|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.16|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.17|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.2|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.3|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.4|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.5|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.6|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.7|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.8|don't install laravel/framework v5.5.0
    - don't install illuminate/config v4.2.9|don't install laravel/framework v5.5.0
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.2, v5.5.3].
    - Installation request for fadion/maneuver ~1.0 -> satisfiable by fadion/maneuver[1.0, 1.0.1, 1.0.2].

**Comment by fadion** [comment]
That package has been organised to support Laravel 4 (for historical users) with version 1.0, Laravel 5.0 - 5.4 with version 2.0, and Laravel 5 with version 2.1. Please check the instructions in the Readme.
