### ISSUE TITLE
Laravel 5.5 support broken?

### ISSUE THREAD

**Issue by tbergeron** [fadion/Maneuver#29]
While on the `dev-l5` branch, I'm getting this error while trying to deploy on an upgraded Laravel 5.5 install:

```
anon@devbox:~/$ php artisan deploy:list
  [ReflectionException]
  Method Fadion\Maneuver\Commands\ListCommand::handle() does not exist

anon@devbox:~/$ php artisan deploy
  [ReflectionException]
  Method Fadion\Maneuver\Commands\DeployCommand::handle() does not exist
```

I know there has been a lot of changes between 5.1 and 5.5, some about commands so maybe something needs tweaking.

I'll try to figure out what exactly did change and broke Maneuver and report my findings here.

Thanks!

**Comment by forelabs** [comment]
I have simply added
```
    public function handle() {
      $this->fire();
    }
```

for now, so it works.
Looks like `fire()` call has been reworked to `handle()`

**Comment by tbergeron** [comment]
@forelabs thanks for pointing that out! I didn't have time to check why it was happening, if this works for me as well I'll open up a PR so @fadion can get this fixed.

**Comment by tbergeron** [comment]
@forelabs I opened a PR with your fix thanks to you! You're awesome! 👍

**Comment by tbergeron** [comment]
I'll leave this opened while @fadion checks if the PR is okay.

**Comment by fadion** [comment]
The package now supports Laravel 5.5 from version 2.1.0. I'm closing this issue, but please let me know if anything's wrong.
