### ISSUE TITLE
Cannot upload files on server / revision file problem?

### ISSUE THREAD

**Issue by tbergeron** [fadion/Maneuver#31]
Hi,

I tried my best to debug that one but here I am begging for help again! 🙉  

In `Deploy.php:241` I get this error while trying to deploy with the latest version. What I find weird at first hand is that it says "fresh deployment" but it shouldn't.

```
+ --------------- § --------------- +
» Server: production
» Fresh deployment - grab a coffee
+ --------------- + --------------- +file_put_contents(ssh2.sftp://Resource id #387/home/deploy/radiotalbot.tv//.gitattributes): failed to open stream: operation failed
```

I tried modifying the remote directory permissions to no avail, I also tried to wipe the remote directory and let Maneuver do its magic. I double-checked, there's a `.revision` file on the remote server.

I don't see what's up with that, could it be a bug or my setup acting up? Or could it be a bug related to https://github.com/banago/Bridge?

Thanks as always!

**Comment by fadion** [comment]
The remote path looks like it's missing something. Note the double slash in:
`/home/deploy/radiotalbot.tv//.gitattributes`

Is there supposed to be a directory in between or is it just an extra slash?

That generic "failed to open stream: operation failed" on file_put_contents() is usually an indicator on denied permissions. Apart from that extra slash, the URL seems to be well constructed on Bridge's side.

**Comment by fadion** [comment]
While you investigate on your part, I'll try to recreate your setup tomorrow first thing. It's something I had to do anyway to test the package after the recent changes.

**Comment by tbergeron** [comment]
This is now fixed on the latest version, everything is working perfectly. Thanks!
