### ISSUE TITLE
Continue from stop 

### ISSUE THREAD

**Issue by Penderis** [fadion/Maneuver#4]
Hi great plugin, but could you please note if possible to continue from a specified point or at least write a marker into the revision file to what last batch was uploaded if ftp fails to continue, I currently am syncing the vendor foler in laravel and just want to complete one sync after which my autoloads will be the only things truly getting loaded but as keeps failing and never completes a full run

**Comment by Penderis** [comment]
Ok so it think I fix as follow, sync my git then ftp the synced files then run deploy --sync with appropriate hash for commit, meaning all three points git,local and server will have same files. but it still be nice if it just tracked its own progress within the commit it uploading.

**Comment by fadion** [comment]
As the file tree is read from git, tracking the progress would be a quite complicated. That's a route this plugin will probably never take.

I've run into your issue myself, especially with folders not being able to be created and the upload process failing. It started to happen when I implemented a ftp and ssh transferring library, which I'll look into for a fix.

What exactly happened while uploading? Did a file transfer fail or while creating a folder?

**Comment by Penderis** [comment]
Hi was just bit confused then remembered you just reading the git commit, so as you know the vendor list for laravel can get pretty massive, so it would run the ftp command and all is well - File uploaded

Then it just stops and reads something like mkdir()5 - assuming this is a folder error -whatever the case may be, I wrongly assumed that even though ftp fails the .revision would maybe just mark at which file it last saved and with deploy continue from that file within the commit list. 

As mentioned I solved this with forcing a sync and ftp with filezilla. So it is not possible to mark the file url that was the last success saved file? 

Thank you for a very useful plugin though, it just one nuance I had but lucky it not crippling.

**Comment by fadion** [comment]
Yes, the mkdir() function is the one I've seen failing too and will definitely look to fix it.

The /vendor folder gets pretty massive and we're supposed to run `composer install` on the server. I guess you don't have ssh access in your server though.

**Comment by Penderis** [comment]
Hi yes shared hosting, so my flow is git commit, then use maneuver to match the commits and then from local repo ftp to live server. 

I think if might simply be failing because, for instance if using filezilla it re-establishes connection , but now on fail cannot call reconnect and even if did call reconnect no way to truly continue from last uploaded file since it a direct link to the commit log.
