### ISSUE TITLE
Oh snap: Unsupported protocol 'ssh2'

### ISSUE THREAD

**Issue by emilsgulbis** [fadion/Maneuver#5]
Hello there!

I have this error after running 'php artisan deploy' to deploy laravel on sftp server.

I've tried 'sftp' instead of 'ssh2', too. 

'production' => array(
            'scheme'    => 'ssh2',
            'host'      => 'host.com',
            'user'      => 'name',
            'pass'      => 'pass',
            'path'      => '/public_html/',
            'port'      => 22,
            'passive'   => true
        ),

**Comment by fadion** [comment]
My bad! Protocol should be `ssh` or `sftp`, not `ssh2`. Please try it again and let me know.

**Comment by emilsgulbis** [comment]
Thanks for fast supporting!

but..

Oh snap: Unsupported protocol 'ssh'

**Comment by fadion** [comment]
Do you have the [ssh2 pecl](http://php.net/book.ssh2) extension installed and enabled? Bridge, the package that Maneuver uses for ftp and sftp transfers depends on that extension. Unfortunately, afaik, there's no better alternative to the pecl extension for ssh operations.

Depending on the system you have, search online for a guide on installing it locally. It shouldn't take more than a few minutes.

I'll make an issue at Bridge for a better error message when ssh2 isn't installed.

**Comment by emilsgulbis** [comment]
![screen shot 2015-01-21 at 20 44 24](https://cloud.githubusercontent.com/assets/3534160/5842537/4ea5df78-a1ae-11e4-97db-c0091fba89bb.png)

I think this means, that I've successfully installed pecl extension, but still..
![screen shot 2015-01-21 at 20 45 11](https://cloud.githubusercontent.com/assets/3534160/5842552/69845e0a-a1ae-11e4-8766-4820fea8b32e.png)

**Comment by emilsgulbis** [comment]
Brew helped me to install ssh2 pecl, but now... 

> Oh snap: ssh2_connect() expects parameter 2 to be long, string given

**Comment by banago** [comment]
There's something wrong with your configs in this last issue.

**Comment by fadion** [comment]
@banago ssh2_connect() expects the port as an Int, not String. I'll open a pull request.

**Comment by emilsgulbis** [comment]
I had int 22 in my config as port

**Comment by fadion** [comment]
Bridge converted the port to string. It is fixed now: https://github.com/banago/Bridge/blob/master/src/Backend/Ssh2.php#L48
